blank_issues_enabled: false
contact_links:
  - name: TearDrops Support
    url: https://discord.gg/GzxwJCJDSs
    about: Please ask any doubts, queries or ask for help in here...(If no one responds, ping @Tissue)
